export const KENYAN_LOCATIONS = [
  { slug: 'nairobi', name: 'Nairobi', region: 'Nairobi County' },
  { slug: 'mombasa', name: 'Mombasa', region: 'Coast Region' },
  { slug: 'kisumu', name: 'Kisumu', region: 'Nyanza Region' },
  { slug: 'nakuru', name: 'Nakuru', region: 'Rift Valley' },
  { slug: 'eldoret', name: 'Eldoret', region: 'Uasin Gishu' },
  { slug: 'thika', name: 'Thika', region: 'Kiambu County' },
  { slug: 'malindi', name: 'Malindi', region: 'Kilifi County' },
  { slug: 'kitale', name: 'Kitale', region: 'Trans Nzoia' },
  { slug: 'garissa', name: 'Garissa', region: 'North Eastern' },
  { slug: 'kakamega', name: 'Kakamega', region: 'Western Region' },
  { slug: 'nyeri', name: 'Nyeri', region: 'Central Region' },
  { slug: 'meru', name: 'Meru', region: 'Eastern Region' },
  { slug: 'embu', name: 'Embu', region: 'Eastern Region' },
  { slug: 'kericho', name: 'Kericho', region: 'Rift Valley' },
  { slug: 'machakos', name: 'Machakos', region: 'Eastern Region' },
  { slug: 'voi', name: 'Voi', region: 'Taita Taveta' },
  { slug: 'naivasha', name: 'Naivasha', region: 'Nakuru County' },
  { slug: 'narok', name: 'Narok', region: 'Narok County' },
  { slug: 'kajiado', name: 'Kajiado', region: 'Kajiado County' },
  { slug: 'kisii', name: 'Kisii', region: 'Nyanza Region' },
];
